ALTER TABLE feedback_history
MODIFY COLUMN new_status ENUM('PENDING', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', 'APPROVED', 'AWAITING_APPROVAL') NOT NULL;

ALTER TABLE feedback_history
MODIFY COLUMN previous_status ENUM('PENDING', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', 'APPROVED', 'AWAITING_APPROVAL') NOT NULL;
